### ISSUE TITLE
Quero participar

### ISSUE THREAD

**Issue by angelica-oliv** [androiddevbr/como-contribuir#1]
* **Descrição:** Gostaria de contribuir na análise dos artigos do Medium.
* **Disponibilidade:** Dependendo da semana, acredito que conseguiria contribuir com 2h ~ 4h por semana em média. 
* **Experiência prévia:** Já escrevi alguns artigos para o Android Dev BR, também para o Pro Android Dev, sou da organização do GDG-SP organizando os Android Meetups e também da organização do Kotlin Meetup SP.
* **Contato:** Angélica Oliveira, angelica.liv@gmail.com

**Comment by orafaaraujo** [comment]
Oi, @angelica-oliv 
Obrigado pelo issue 🎉

Estou conversando qual seria a melhor forma de fazermos o onboarding. Entraremos em contato em breve. :)
