### ISSUE TITLE
Link do canal do slack indisponível

### ISSUE THREAD

**Issue by joaocarvoli** [androiddevbr/como-contribuir#4]
Olá, pessoal!

Encontrei a comunidade de vocês hoje após algumas pesquisas e gostaria de saber se vocês poderiam enviar um novo convite para o canal do slack. :) Esse é o link que tenho tentado acessar: http://slack.androiddevbr.org

Erro mostrado:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/62486484/236079691-8f2ca9db-8c2b-484d-9018-1529949b6253.png">

**Comment by khalildevbr** [comment]
Olá @joaocarvoli. Obrigado por entrar em contato avisando do problema com o site de auto invite. Ficamos contentes que queira fazer parte da comunidade. Estamos cientes, mas ainda não tivemos tempo para corrigir o problema. 

Por hora pode usar esse link aqui que gerei para o seu acesso:  https://join.slack.com/t/androiddevbr/shared_invite/zt-1ut4w35zk-zZI1FhSgOT93e0Ho7nlmCg

Qualquer dúvida, problemas etc, por favor, nos avise!

**Comment by joaocarvoli** [comment]
Tudo bem, muito obrigado pela ajuda! Consegui entrar no grupo.
